// frontend/src/components/Content.vue
<script setup lang="ts"></script>
<template>
  <div class="w-full h-full">
    <div
      class="flex justify-center items-centerw-auto max-w-[100%] h-screen border-8 border-[#3b04c67c] shadow shadow-white rounded-[5px]"
    >
      <img
        src="/mem.jpg"
        alt="photo"
        class="w-auto max-w-full object-cover"
      />
    </div>
  </div>
</template>
<style scoped></style>

// frontend/src/components/Content.tsx
import { FC } from "react";
import { Flex } from "../styledComponents/Flex";
import { Image } from "../styledComponents/Image";
import { Container } from "../styledComponents/Container";

export const Content: FC = () => {
  return (
    <Container $width="100%" height="100%">
      <Flex
        width="100%"
        height="100%"
        $justify="center"
        $align="center"
        $border="10px solid #3b04c67c"
        $boxShadow="0 0 0 2px white"
        $borderRadius="5px"
      >
        <Image
          width="100%"
          $cover="cover"
          height="fit-content"
          src="../../public/mem.jpg"
        />
      </Flex>
    </Container>
  );
};
