// frontend/src/components/Date.vue
<script setup lang="ts">
const today = new Date();
</script>
<template>
  <div
    class="flex w-full justify-center items-center bg-[#0c0c23] text-white h-[80px]"
    style="grid-area: 1 / 1 / 2 / 2"
  >
    <p class="text-[3rem]">{{ today.toLocaleDateString() }}</p>
  </div>
</template>
<style scoped></style>

// frontend/src/components/Date.tsx
import { FC } from "react";
import { Paragraph } from "../styledComponents/Paragraph";
import { Flex } from "../styledComponents/Flex";

export const DateBlock: FC = () => {
  const today = new Date();

  return (
    <Flex
      width="100%"
      $gridArea="1 / 1 / 2 / 2"
      $justify="center"
      $align="center"
      $bgColor="#0c0c23"
    >
      <Paragraph $fontSize="3rem">{today.toLocaleDateString()}</Paragraph>
    </Flex>
  );
};
